package com.paymentledger.reconciliation.domain;

public enum DiscrepancyType {
    PROVIDER_SUCCESS_LOCAL_PENDING,
    PROVIDER_FAILURE_LOCAL_PENDING,
    PROVIDER_UNKNOWN,
    PROVIDER_MISMATCH,
    LOCAL_FINANCIAL_STATE_MISSING,
    LEDGER_STATE_MISMATCH,
    DUPLICATE_OPERATION,
    ALREADY_RESOLVED,
    NON_RECONCILABLE
}
